name: Release Pipeline

on:
  push: {}

jobs:
  release-pipeline:
    name: Release Pipeline
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Run Core Tests
        shell: pwsh
        run: dotnet test ./.\src\DevOpsDaysTasks.Core.Tests
    

      - name: Hello Pipeline
        shell: pwsh
        run: echo "Hello from the Pipeline"